Repository SalamLang/.github, pull requests merged in 2025-10, with the labels that each got.

#3 Update README.md add team members section
  profile/README.md
Labels: documentation

#11 Update README.md add another milestone hack fest link
  profile/README.md
Labels: documentation

#12 Update README.md order hack fest links
  profile/README.md
Labels: documentation

#14 Update README.md add hack fest info for Salam-Editor
  profile/README.md
Labels: documentation

#17 Issue16
  .github/linters/.markdownlint.json
  .github/linters/.yamllint.yaml
  .pre-commit-config.yaml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, tests

#24 Add official pre-commit hooks for better code quality #22
  .pre-commit-config.yaml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, yaml, tests

#25 Add basic .editorconfig file for consistent coding styles (#23)
  .editorconfig
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#27 Add codespell to pre-commit
  .pre-commit-config.yaml
  README.md
  profile/README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, yaml, tests
